### ISSUE TITLE
Feature Request: About

### ISSUE THREAD

**Issue by danrobi11** [ZorrillosDev/watchit-app#48]
## Feature Request:
- Delete option # Option to delete the movie. 
- About option # About with Github link and version

## Questions:
* Once a movie is downloaded. Wheres the movie location ?
* Are we seeding downloaded movies ? If yes, need option to copy the CID in order to seed from IPFS-desktop etc.

**Comment by geolffreym** [comment]
Hi @danrobi11 thank you for create an issue. 
"**Delete option # Option to delete the movie**" -> When you say you want to delete the movie, do you mean you want a tool to remove temporary download files or movie metadata from the local database?

"**About option # About with Github link and version**" -> Great idea!! It is a good idea to add to our roadmap, although maybe we could have it sooner with the help of the community, maybe you are interested in exploring the code a bit and send us your PR;).


**Once a movie is downloaded. Wheres the movie location ?**
HLS does not download it the movie it's buffered, in the torrent stream case they are stored in **/tmp** folder

**Are we seeding downloaded movies ? If yes, need option to copy the CID in order to seed from IPFS-desktop etc.**
The application shares movies with the network depending on the streaming mechanism. In the case of torrents you share parts of the movie that you are watching while others share you, in the case of HLS it is very similar but in this case it depends if your node has the movie in the local repo, that is to say If you already saw the movie then it is temporarily cached on the local IPFS node and if someone else wants to see the same movie that you watched then your node will have the expected behavior of transmitting part of the movie if another node requests it (BitSwap).

**Comment by danrobi11** [comment]
Thanks for the support @geolffreym 

> remove temporary download files or movie metadata from the local database?

Yes. Delete option would be nice to delete the cached movies.

> maybe you are interested in exploring the code a bit and send us your PR

Unfortunately, I do not code :/

Closing

**Comment by geolffreym** [comment]
@danrobi11 adding features to roadmap!!

**Comment by geolffreym** [comment]
@all-contributors please add @danrobi11 for ideas, userTesting, bug

**Comment by geolffreym** [comment]
Show: 
GitHub link
Current version

**Comment by danrobi11** [comment]
> The application shares movies with the network depending on the streaming mechanism. In the case of torrents, you share parts of the movie only when you are watching it while others share you (TorrentNetwork). In the case of HLS it is very similar but in this case it depends if your node has the movie in the local repo, that is, if you have already watch the "movie" then it is temporarily cached in the local IPFS node and if someone else wants to watch the same "movie" then your node will have the expected behavior of transmitting part of the movie if another node requests it (BitSwap).

To make things easier. 

1- Delete file option in the file page. Page with the play, trailer and description   
2- Copy CID option. In the same page as above.

That way we could help seeding and manage as we please our files.
I share my blog, website etc over IPFS. My node run 24/7.

I've tested the new v0.1.0-beta.8. Now the file that I previously loaded is gone. I'll have to load the file again.
It would be better if the user could manage how they want to deal with the files.

**Comment by geolffreym** [comment]
Keep  “about” feature in this thread
